name: scan-container-for-vulnerabilities
run-name: ${{ github.actor }} is vulnerability scanning Container
on:
  schedule:
    - cron: '0,15,30,45 * * * *'
jobs:
  scan-for-container-vulnerabilty:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: msaginwm/devsecops-base:latest
      -
        name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: msaginwm/devsecops-base:latest
          dockerfile: ./Dockerfile
      -
        name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}    
